version: '2'
services: 
  backend:
    restart: always
    # container_name: myu_frontend
    build: './backend'
    volumes:
      - './backend:/app'
    ports:
      - '3030:3030'
    depends_on:
      - mongodb
  
  frontend:
    # container_name: myu_frontend
    restart: always
    build: './frontend'
    volumes:
      - './frontend:/app'
    ports:
      - '8080:8080'

  mongodb:
    # container_name: myu_mongodb
    restart: always
    image: mongo
    volumes:
      - './mongodb:/data/db'
    ports:
      - "27017:27017"
  nginx:
    # container_name: myu_nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend